[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

#[[plugins]]
#"repo = 'delphinus35/typescript-vim'
#"rev  = 'colorize-template-strings'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

#[[plugins]]
#repo    = 'vim-airline/vim-airline'
#depends = ['vim-airline-themes']


[[plugins]]
repo    = 'scrooloose/nerdtree'

# Git
[[plugins]]
repo = "airblade/vim-gitgutter"
[[plugins]]
repo = "tpope/vim-fugitive"




[[plugins]]
repo = 'thinca/vim-quickrun'


[[plugins]]
repo = 'millermedeiros/vim-esformatter'
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','md']



[[plugins]]
repo = 'mattn/emmet-vim'


[[plugins]]
repo = 'thinca/vim-quickrun'


######## git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = "airblade/vim-gitgutter"

## Typescript 

[[plugins]]
repo = 'leafgarland/typescript-vim'
[[plugins]]
repo='clausreinke/typescript-tools'

## go lang
[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'honza/vim-snippets'


[[plugins]]
repo='rust-lang/rust.vim'

