[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','md']



[[plugins]]
repo = 'mattn/emmet-vim'


[[plugins]]
repo = 'thinca/vim-quickrun'


######## git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = "airblade/vim-gitgutter"

## Typescript 

[[plugins]]
repo = 'leafgarland/typescript-vim'
[[plugins]]
repo='clausreinke/typescript-tools'
